# Generated by Django 4.2 on 2024-06-19 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chats', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chat',
            name='views_at',
        ),
        migrations.AddField(
            model_name='chat',
            name='viewed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='chatmessage',
            name='viewed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
